import { test, expect } from '@playwright/test'
import { readFile } from 'node:fs/promises'
import { Buffer } from 'node:buffer'

const palette = {
  '外框': 'bbb181', '外框饰条': 'bbb181', '玻璃': 'f0f0f0', '内部面板': 'bbd095',
  '内部金属': 'd0e7d0', '主板': 'b8c59b', '凹槽与风扇底色': 'cecb69', '管线': 'd5ddc6',
}
async function start(page) {
  await page.goto('/?lookdev=1&panel=computer')
  await expect(page.locator('.workbench-canvas')).toHaveAttribute('data-state', 'ready', { timeout: 60000 })
  await expect(page.locator('.site-loader')).toHaveCount(0, { timeout: 30000 })
  await expect(page.locator('.computer-case-panel')).toBeVisible()
}
const control = (page, label) => page.locator('.computer-case-panel .lookdev-control').filter({ has: page.getByText(label, { exact: true }) }).locator('input[type="number"]')

test('case palette, layout, attached routes and draft roundtrip work through the console', async ({ page }) => {
  const errors = []; page.on('pageerror', error => errors.push(error.message))
  await start(page)
  for (const [label, color] of Object.entries(palette)) await expect(page.getByRole('textbox', { name: `${label} HEX`, exact: true })).toHaveValue(color)
  await expect(control(page, '粗糙度')).toHaveValue('0.36')
  await expect(control(page, '不透明度')).toHaveValue('0.2')
  await expect(control(page, '宽度')).toHaveValue('520.2')
  await expect(control(page, '左右')).toHaveValue('14')
  await expect(control(page, '前后')).toHaveValue('-124')
  const initial = Number(await page.locator('.workbench-canvas').getAttribute('data-camera-distance'))
  await page.getByRole('button', { name: '机箱近景', exact: true }).click()
  await expect.poll(async () => Number(await page.locator('.workbench-canvas').getAttribute('data-camera-distance'))).toBeLessThan(initial)
  await page.getByRole('textbox', { name: '内部金属 HEX', exact: true }).fill('bbccaa')
  await page.getByRole('textbox', { name: '内部金属 HEX', exact: true }).press('Enter')
  await control(page, '高度').fill('90')
  await control(page, '上下').fill('20')
  await page.getByRole('combobox', { name: '机箱部件' }).selectOption('coolant-1')
  await control(page, '管线直径').fill('16')
  await control(page, '前后').fill('25')
  await page.getByRole('button', { name: 'Save draft', exact: true }).click()
  const saved = await page.evaluate(() => JSON.parse(localStorage.getItem('jiaqi-workstation-lookdev-draft')))
  expect(saved.computer.parts.gpu.heightMm).toBe(90)
  expect(saved.computer.parts.gpu.yMm).toBe(20)
  expect(saved.computer.parts['coolant-1'].diameterMm).toBe(16)
  expect(saved.computer.parts['coolant-1'].bendZmm).toBe(25)
  await start(page)
  await expect(control(page, '高度')).toHaveValue('90')
  await expect(control(page, '上下')).toHaveValue('20')
  await expect(page.getByRole('textbox', { name: '内部金属 HEX', exact: true })).toHaveValue('bbccaa')
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: '导出参数', exact: true }).click()
  const exported = await download, contents = JSON.parse(await readFile(await exported.path(), 'utf8'))
  expect(contents.computer).toEqual(saved.computer)
  await page.getByRole('button', { name: '恢复整个机箱', exact: true }).click()
  await expect(control(page, '上下')).toHaveValue('0')
  await expect(page.getByRole('textbox', { name: '内部金属 HEX', exact: true })).toHaveValue('d0e7d0')
  await page.locator('.lookdev-import input').setInputFiles({ name: 'case-draft.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(contents)) })
  await expect(control(page, '上下')).toHaveValue('20')
  await page.getByRole('combobox', { name: '机箱部件' }).selectOption('coolant-1')
  await expect(control(page, '管线直径')).toHaveValue('16')
  await page.getByRole('button', { name: '工作台整体', exact: true }).click()
  await expect(page.locator('.workbench-canvas')).toHaveAttribute('data-moving', 'false', { timeout: 10000 })
  await expect.poll(async () => Number(await page.locator('.workbench-canvas').getAttribute('data-camera-distance'))).toBeCloseTo(initial, 3)
  await page.getByRole('button', { name: '恢复整个机箱', exact: true }).click()
  await page.getByRole('button', { name: '机箱近景', exact: true }).click()
  await page.screenshot({ path: 'docs/qa/computer-case-console-2026-10-09/desktop.png' })
  expect(errors).toEqual([])
})

test('mobile case console stays usable and is absent from the regular page', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  const stale = { version: 1, materials: { Computer_case_smoked_glass: { color: 'ff0000' } } }
  await page.addInitScript(draft => localStorage.setItem('jiaqi-workstation-lookdev-draft', JSON.stringify(draft)), stale)
  await start(page)
  await expect(page.getByRole('textbox', { name: '玻璃 HEX', exact: true })).toHaveValue('f0f0f0')
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem('jiaqi-workstation-lookdev-draft')))).toEqual(stale)
  await page.getByRole('button', { name: '机箱近景', exact: true }).click()
  await page.getByRole('combobox', { name: '机箱部件' }).selectOption('rear-fan')
  await control(page, '厚度／深度').fill('80')
  await page.getByRole('button', { name: '恢复当前部件', exact: true }).click()
  const bounds = await page.locator('.lookdev-panel').boundingBox()
  expect(bounds.x).toBeGreaterThanOrEqual(0)
  expect(bounds.x + bounds.width).toBeLessThanOrEqual(390)
  await page.screenshot({ path: 'docs/qa/computer-case-console-2026-10-09/mobile.png' })
  await page.goto('/')
  await expect(page.locator('.lookdev-panel')).toHaveCount(0)
})

test('material selection exposes outer surfaces and restores approved component sizes', async ({ page }) => {
  await start(page)
  const material = page.getByRole('combobox', { name: '材质属性', exact: true })
  const linked = page.getByRole('combobox', { name: '材质对应部件', exact: true })
  await material.selectOption('Computer_case_smoked_glass')
  await expect(linked).toHaveValue('glass')
  await page.getByRole('button', { name: '调整对应部件的尺寸与位置', exact: true }).click()
  await control(page, '宽度').fill('420')
  await control(page, '高度').fill('460')
  await control(page, '厚度／深度').fill('8')
  await control(page, '上下').fill('35')
  await material.selectOption('Computer_case_warm_shell')
  await expect(linked).toHaveValue('shell')
  await expect(control(page, '不透明度')).toHaveValue('0')
  await expect(page.locator('.computer-case-panel .lookdev-control').filter({ has: page.getByText('不透明度', { exact: true }) }).locator('input[type="range"]')).toHaveValue('0')
  await control(page, '高度').fill('570')
  await control(page, '上下').fill('12')
  await material.selectOption('Computer_case_sage_accent')
  await expect(linked).toHaveValue('accent')
  await control(page, '高度').fill('500')
  await material.selectOption('Computer_internal_warm_white')
  await linked.selectOption('back-panel')
  await control(page, '上下').fill('10')
  await page.getByRole('button', { name: 'Save draft', exact: true }).click()
  const saved = await page.evaluate(() => JSON.parse(localStorage.getItem('jiaqi-workstation-lookdev-draft')))
  expect(saved.computer.parts.glass).toMatchObject({ widthMm: 420, heightMm: 460, depthMm: 8, yMm: 35 })
  expect(saved.computer.parts.shell).toMatchObject({ heightMm: 570, yMm: 12 })
  expect(saved.computer.parts.accent.heightMm).toBe(500)
  await start(page)
  await material.selectOption('Computer_case_smoked_glass')
  await expect(control(page, '宽度')).toHaveValue('420')
  await expect(control(page, '上下')).toHaveValue('35')
  await page.getByRole('button', { name: '恢复整个机箱', exact: true }).click()
  await page.getByRole('combobox', { name: '机箱部件' }).selectOption('gpu')
  await expect(control(page, '宽度')).toHaveValue('520.2')
  await expect(control(page, '左右')).toHaveValue('14')
  await control(page, '宽度').fill('450')
  await page.getByRole('button', { name: '恢复当前部件', exact: true }).click()
  await expect(control(page, '宽度')).toHaveValue('520.2')
  await page.getByRole('combobox', { name: '机箱部件' }).selectOption('glass')
  await page.getByRole('button', { name: '机箱近景', exact: true }).click()
  await page.getByRole('button', { name: '调整对应部件的尺寸与位置', exact: true }).click()
  await page.screenshot({ path: 'docs/qa/computer-case-console-2026-10-09/outer-surfaces.png' })
})
