import { test, expect } from '@playwright/test'

const settled = page => expect(page.locator('#root')).not.toHaveAttribute('data-transitioning', 'true')

test('full curved transition keeps its duration and Contact has its own layout', async ({ page }) => {
  const errors = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/about')
  await page.getByRole('navigation', { name: 'Main navigation' }).getByRole('link', { name: 'Contact', exact: true }).click()
  await expect(page.locator('html')).toHaveAttribute('data-route-motion', 'page')
  await expect(page.locator('.reference-contact h1')).toHaveText('Let’s talk.')
  await page.waitForTimeout(750)
  await expect(page.locator('#root')).toHaveAttribute('data-transitioning', 'true')
  const effects = await page.evaluate(() => document.getAnimations().map(animation => ({ name: animation.animationName, duration: animation.effect.getTiming().duration, delay: animation.effect.getTiming().delay })))
  expect(effects).toContainEqual({ name:'route-curve', duration:1950, delay:0 })
  expect(effects).toContainEqual({ name:'route-finish', duration:180, delay:1770 })
  expect(effects).toContainEqual({ name:'route-page-arrive', duration:650, delay:1300 })
  await page.screenshot({ path:'docs/qa/motion/transition-0750.png' })
  await settled(page)
  await expect(page.locator('.reference-about')).toHaveCount(0)
  await expect(page.locator('.contact-links a')).toHaveCount(2)
  await page.screenshot({ path:'docs/qa/motion/contact-desktop.png' })
  await page.goBack(); await settled(page)
  await expect(page.locator('.reference-about')).toBeVisible()
  expect(errors).toEqual([])
})

test('gallery expands the selected photograph and returns to the same strips and scroll position', async ({ page }) => {
  await page.goto('/photography')
  await page.waitForTimeout(1500)
  await expect(page.getByText(/Pause gallery|PHOTOGRAPHS|Hover to pause|For commissions/)).toHaveCount(0)
  await expect(page.locator('.gallery-row-heading h2').first()).toHaveText('Portraits')
  await expect(page.locator('.gallery-row-heading h2').last()).toHaveText('Selected moments')
  const link = page.locator('.gallery-group').first().getByRole('link').nth(2)
  await link.focus()
  await page.waitForTimeout(650)
  const before = await page.locator('.gallery-track').evaluateAll(els => els.map(el => Number(el.dataset.offset)))
  const scroll = await page.evaluate(() => window.scrollY)
  await page.keyboard.press('Enter')
  await expect(page.locator('html')).toHaveAttribute('data-route-motion','photo-open')
  await expect(page.locator('.series-selected img')).toHaveAttribute('data-photo-id','portrait-03')
  await page.waitForTimeout(150)
  const names = await page.evaluate(() => document.getAnimations().map(a => a.effect?.pseudoElement))
  expect(names).toContain('::view-transition-group(selected-photo)')
  await page.screenshot({ path:'docs/qa/motion/photo-expansion.png' })
  await settled(page)
  await page.getByRole('link', { name:'Back to gallery', exact:true }).click()
  await expect(page.locator('html')).toHaveAttribute('data-route-motion','photo-close')
  await page.waitForTimeout(100)
  const restored = await page.locator('.gallery-track').evaluateAll(els => els.map(el => Number(el.dataset.offset)))
  // Only a few milliseconds elapse between keyboard activation and the outgoing capture.
  expect(Math.abs(restored[0] - before[0])).toBeLessThan(2)
  expect(Math.abs(restored[1] - before[1])).toBeLessThan(5)
  expect(await page.evaluate(() => window.scrollY)).toBe(scroll)
  await settled(page)
  await page.screenshot({ path:'docs/qa/motion/gallery-desktop.png' })
})

test('photography navigation scrolls out, cursor is contextual, and mobile stays clear', async ({ page }) => {
  await page.goto('/photography')
  await page.waitForTimeout(1400)
  const image = page.locator('.gallery-group').first().getByRole('link').nth(1)
  const box = await image.boundingBox()
  await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2)
  await expect(page.locator('.follow-cursor')).toHaveAttribute('data-visible','true')
  await expect(page.locator('.follow-cursor')).toHaveText('View photograph↗')
  await page.mouse.move(650,30)
  await expect(page.locator('.follow-cursor')).not.toHaveAttribute('data-visible','true')
  await page.setViewportSize({ width:390, height:600 })
  await page.evaluate(() => window.scrollTo(0,300))
  expect(await page.locator('.canvas-identity').evaluate(el => el.getBoundingClientRect().bottom)).toBeLessThan(0)
  expect(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth)).toBe(false)
  await page.screenshot({ path:'docs/qa/motion/gallery-mobile-scrolled.png' })
  await page.goto('/contact')
  await page.setViewportSize({ width:390,height:844 })
  await page.waitForTimeout(1200)
  await page.screenshot({ path:'docs/qa/motion/contact-mobile.png' })
})

test('reduced motion and a browser without snapshot transitions still navigate and return', async ({ page }) => {
  await page.addInitScript(() => { document.startViewTransition = undefined })
  await page.goto('/photography')
  await page.locator('.gallery-group').first().getByRole('link').nth(1).focus()
  await page.keyboard.press('Enter')
  await expect(page.locator('.series-selected img')).toHaveAttribute('data-photo-id','portrait-02')
  await page.getByRole('link',{name:'Back to gallery',exact:true}).click()
  await expect(page.locator('.gallery-track')).toHaveCount(2)
  await page.emulateMedia({ reducedMotion:'reduce' })
  await page.getByRole('navigation',{name:'Main navigation'}).getByRole('link',{name:'Contact',exact:true}).click()
  await expect(page.locator('.reference-contact')).toBeVisible()
  await expect(page.locator('#root')).not.toHaveAttribute('data-transitioning')
  await expect(page.locator('.follow-cursor')).toBeHidden()
})


test('static mobile gallery remembers horizontal position after opening and closing a photo', async ({ page }) => {
  await page.setViewportSize({ width:390,height:844 })
  await page.emulateMedia({ reducedMotion:'reduce' })
  await page.goto('/photography')
  const row = page.locator('.gallery-viewport').first()
  await row.evaluate(el => { el.scrollLeft = 300 })
  const photo = row.getByRole('link').nth(2)
  await photo.click()
  await expect(page.locator('.series-selected img')).toHaveAttribute('data-photo-id','portrait-03')
  await page.getByRole('link',{name:'Back to gallery',exact:true}).click()
  await expect(page.locator('.gallery-viewport').first()).toHaveJSProperty('scrollLeft',300)
})
