"""Build responsive photo derivatives without changing the original portfolio files.

Run with Python 3 and Pillow. Orientation is normalized, metadata is omitted from
derivatives, and all sizes are measured from decoded images. The gallery order is
the order published in the original MainPhotos.jsx.
"""

from pathlib import Path
import json

from PIL import Image, ImageOps


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "public/images/photos"
DATA = ROOT / "src/data/photographs.js"

# Descriptions are based on visual inspection, without invented names/locations.
GALLERY = [
    ("4071744705063_.pic.jpg", "Close portrait with green leaves casting shadows across a smiling face."),
    ("A060541-R1-13-13A.jpg", "Person in a tan coat holding flowers in a sunlit city square."),
    ("A060541-R1-25-25A.JPG", "Person in a coat and scarf holding a takeaway cup beside the water."),
    ("4041744705063_.pic.jpg", "Person leaning against a pale green wall with a bright bouquet."),
    ("4061744705063_.pic.jpg", "Smiling person in a grey scarf beside a city square, photographed at an angle."),
    ("4051744705063_.pic.jpg", "Person in a dark coat resting against a sunlit stone wall with hands raised."),
    ("A060541-R1-24-24A.JPG", "Portrait in a tan coat and thick scarf beside a waterfront railing."),
    ("4001744704883_.pic.jpg", "Person in a pink top looking into a bathroom mirror above a row of toiletries."),
    ("b479ae331017cd34f3a9815183419bd7.JPG", "Sunlit close portrait of a person resting their face on a grey knitted sleeve."),
    ("IMG_4622.JPG", "Black and white close portrait with bold eye makeup and a small facial decoration."),
    ("4121744705200_.pic.jpg", "Smiling person holding flowers near a chain railing in bright sunlight."),
    ("b1b6c60d3ff45dfec850b281454ea903.JPG", "Overhead portrait of a person reclining on blue fabric with a patterned snake."),
    ("4091744705200_.pic.jpg", "Person resting their arms beside a teacup on a lace-covered table."),
    ("4111744705200_.pic.jpg", "Outdoor portrait of a smiling person with orange and yellow flowers against green foliage."),
    ("4101744705200_.pic.jpg", "Person holding a bright bouquet beside a softly lit window."),
    ("3991744704883_.pic.jpg", "Person seated by a small lace-covered table, surrounded by large green leaves."),
    ("P1011157.jpg", "Person leaning across a lace-covered table beside a teacup and a leafy plant."),
    ("IMG_4351.jpg", "Person in a light coat holding a bouquet with eyes closed against a sunlit wall."),
    ("IMG_4352.JPG", "Close portrait of a person with flowers, looking into warm sunlight."),
]
ABOUT = [
    ("IMG_5427.jpg", "Outdoor portrait of a person wearing glasses and a striped T-shirt."),
    ("IMG_5429.JPG", "Smiling person in a denim shirt and green jacket against dark foliage."),
]


def prepare(filename, alt, photo_id):
    source = ROOT / "public/photos" / filename
    with Image.open(source) as original:
        photo = ImageOps.exif_transpose(original).convert("RGB")
    width, height = photo.size
    variants = []
    for size in sorted({min(width, target) for target in (480, 960, 1600)}):
        derivative = photo.resize((size, round(height * size / width)), Image.Resampling.LANCZOS)
        path = OUTPUT / f"{photo_id}-{size}.webp"
        derivative.save(path, "WEBP", quality=83, method=6)
        variants.append(f"/images/photos/{path.name} {size}w")

    jpeg_width = min(width, 960)
    jpeg = photo.resize((jpeg_width, round(height * jpeg_width / width)), Image.Resampling.LANCZOS)
    jpeg_path = OUTPUT / f"{photo_id}-{jpeg_width}.jpg"
    jpeg.save(jpeg_path, "JPEG", quality=84, optimize=True, progressive=True)
    original_url = f"/photos/{filename}"
    viewer_variants = list(variants)
    # The original remains available for full-resolution zoom. Avoid duplicate widths.
    if width > min(width, 1600):
        viewer_variants.append(f"{original_url} {width}w")
    else:
        viewer_variants[-1] = f"{original_url} {width}w"
    return {
        "id": photo_id,
        "original": original_url,
        "width": width,
        "height": height,
        "src": f"/images/photos/{jpeg_path.name}",
        "srcSet": ", ".join(variants),
        "viewerSrcSet": ", ".join(viewer_variants),
        "alt": alt,
    }


def main():
    OUTPUT.mkdir(parents=True, exist_ok=True)
    DATA.parent.mkdir(parents=True, exist_ok=True)
    photographs = [prepare(name, alt, f"portrait-{i:02d}") for i, (name, alt) in enumerate(GALLERY, 1)]
    about = [prepare(name, alt, f"about-{i:02d}") for i, (name, alt) in enumerate(ABOUT, 1)]
    DATA.write_text(
        "// Generated by scripts/prepare-photos.py. Original files and gallery order are preserved.\n"
        + "export const photographs = " + json.dumps(photographs, indent=2, ensure_ascii=False) + ";\n\n"
        + "export const aboutPortrait = " + json.dumps(about[0], indent=2, ensure_ascii=False) + ";\n\n"
        + "export const aboutStoryImage = " + json.dumps(about[1], indent=2, ensure_ascii=False) + ";\n"
    )
    size = sum(path.stat().st_size for path in OUTPUT.glob("*"))
    print(f"Prepared {len(photographs)} gallery photos and {len(about)} About photos: {size / 1024 / 1024:.2f} MiB of derivatives.")


if __name__ == "__main__":
    main()
